version: '3.9'
services:
  hazelcast:
    container_name: hazelcast
    ports:
      - '5701:5701'
    image: 'hazelcast/hazelcast:latest-jdk17'
    environment:
      HZ_JET_ENABLED: 'true'
      HZ_JET_RESOURCEUPLOADENABLED: 'true'
  
  #  http://localhost:8091/
  #  Create a new bucket
  couchbase:
    image: couchbase:latest
    container_name: couchbase
    ports:
      - '8091:8091'   # Couchbase Admin UI
      - '8092:8092'   # Couchbase Data Port
      - '8093:8093'   # Couchbase Query Port
      - '8094:8094'   # Couchbase Index Port
      - '8095:8095'   # Couchbase Analytics Port
      - '8096:8096'   # Couchbase Eventing Port
      - '11210:11210' # Couchbase Data Service (main data port)
      - '11211:11211' # Couchbase Memcached Service (legacy port)
    environment:
      - COUCHBASE_ADMIN_USERNAME=admin
      - COUCHBASE_ADMIN_PASSWORD=password
    
# to start containers
# docker compose -f docker-compose-couchbase.yml up

# to remove the volumes
# docker compose -f docker-compose-couchbase.yml down -v
