version: '3.9'
services:
  hazelcast:
    container_name: hazelcast
    ports:
      - '5701:5701'
    image: 'hazelcast/hazelcast:5.4.0-SNAPSHOT'

  management-center:
    image: hazelcast/management-center
    ports:
      - "8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast


# to start containers
# docker-compose up

# to remove the volumes
# docker-compose down -v

# For MC go to
# http://localhost:8080
# and enable dev mode