version: '3.9'
services:
  mysql:
    # environment variables are not a list
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       # root can log in from every host
       MYSQL_ROOT_HOST: '%'
    container_name: mysql
    ports:
      - '3306:3306'
    # For volumes, it will execute files with extensions .sh, .sql and .sql.gz that are found in
    # /docker-entrypoint-initdb.d. Files will be executed in alphabetical order.
    volumes:
      - './mysql_schema.sql:/docker-entrypoint-initdb.d/mysql_schema.sql'
    image: 'mysql:8.0'
    networks:
      - tutorial

networks:
  tutorial:
    driver: bridge

# to start containers
# docker-compose docker compose -f docker-compose-mysql.yml up

# to remove the volumes
# docker-compose docker compose -f docker-compose-mysql.yml up down -v

# login with
# mysql -uroot -proot
